import math
import statistics
from collections import Counter, defaultdict


FULL_THROTTLE_RECURRENCE_VERSION = "1.0"
FULL_THROTTLE_RECURRENCE_SCHEMA_VERSION = "1.0"
FULL_THROTTLE_RECURRENCE_MIN_SUPPORT_COUNT = 2

SUPPORTED_DIRECTIONS = (
    "earlier_in_comparison_lap",
    "later_in_comparison_lap",
    "similar_to_reference",
    "reference_attained_comparison_not_confirmed",
    "comparison_attained_reference_not_confirmed",
)

DIRECTION_PATTERN_KIND = {
    "earlier_in_comparison_lap": "timing",
    "later_in_comparison_lap": "timing",
    "similar_to_reference": "similarity",
    "reference_attained_comparison_not_confirmed": "attainment_state",
    "comparison_attained_reference_not_confirmed": "attainment_state",
}


# ============================================================
# FULL THROTTLE ATTAINMENT RECURRENCE v1.0
# DETERMINISTIC / SESSION-LEVEL / OBSERVATIONAL
# ============================================================
#
# Source of truth:
# - throttle_full_throttle_attainment_comparison generated by
#   throttle_point_v1_2_1 inside each driver_action_episode.
#
# Physical identity:
# - the reference lap is fixed for all comparisons in one analysis;
# - reference_event_id therefore identifies the same physical throttle
#   event across comparison laps.
#
# The aggregator:
# - deduplicates the same reference event inside one comparison;
# - counts repeated timing/state observations across comparison laps;
# - preserves unavailable/missing evidence explicitly;
# - never authorizes coaching;
# - never modifies ranking, priorities or driver_action_episodes;
# - never infers traction, line, balance, wheelspin, intent or causality.
# ============================================================


def _safe_float(value):
    if value is None:
        return None
    try:
        value = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(value):
        return None
    return value


def _safe_int(value):
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _median(values):
    clean = [
        _safe_float(value)
        for value in values
        if _safe_float(value) is not None
    ]
    if not clean:
        return None
    return float(statistics.median(clean))


def full_throttle_recurrence_config_summary():
    return {
        "enabled": True,
        "version": FULL_THROTTLE_RECURRENCE_VERSION,
        "schema_version": FULL_THROTTLE_RECURRENCE_SCHEMA_VERSION,
        "source_detector": "throttle_point_v1_2_1",
        "source_field": "throttle_full_throttle_attainment_comparison",
        "physical_identity": "reference_lap_plus_reference_event_id",
        "min_support_count": FULL_THROTTLE_RECURRENCE_MIN_SUPPORT_COUNT,
        "unavailable_observations_are_contradictions": False,
        "missing_comparisons_are_contradictions": False,
        "observational_only": True,
        "affects_ranking": False,
        "affects_session_priority": False,
        "authorizes_coaching": False,
    }


def _episode_ranking(comparison_output):
    if not isinstance(comparison_output, dict):
        return []

    objective = comparison_output.get("objective_analysis")
    if not isinstance(objective, dict):
        return []

    ranking = objective.get("driver_action_episode_ranking", [])
    return ranking if isinstance(ranking, list) else []


def _candidate_signature(candidate):
    return (
        candidate.get("status"),
        candidate.get("relative_direction"),
        candidate.get("reference_attainment_confirmed"),
        candidate.get("comparison_attainment_confirmed"),
        candidate.get("reference_attainment_m"),
        candidate.get("comparison_attainment_m"),
        candidate.get("comparison_minus_reference_m"),
    )


def _compact_candidate(comparison_output, episode, result):
    return {
        "reference_lap": _safe_int(comparison_output.get("reference_lap")),
        "comparison_lap": _safe_int(comparison_output.get("comparison_lap")),
        "episode_id": episode.get("episode_id"),
        "episode_global_rank": episode.get("global_rank"),
        "zone_id": episode.get("zone_id"),
        "episode_start_m": _safe_float(episode.get("start_distance_m")),
        "episode_end_m": _safe_float(episode.get("end_distance_m")),
        "action_time_loss_s": _safe_float(episode.get("action_time_loss_s")),
        "throttle_pair_id": result.get("throttle_pair_id"),
        "reference_event_id": result.get("reference_event_id"),
        "comparison_event_id": result.get("comparison_event_id"),
        "status": result.get("status"),
        "relative_direction": result.get("relative_direction"),
        "reference_attainment_confirmed": bool(
            result.get("reference_attainment_confirmed")
        ),
        "comparison_attainment_confirmed": bool(
            result.get("comparison_attainment_confirmed")
        ),
        "reference_attainment_m": _safe_float(
            result.get("reference_attainment_m")
        ),
        "comparison_attainment_m": _safe_float(
            result.get("comparison_attainment_m")
        ),
        "reference_onset_to_full_throttle_m": _safe_float(
            result.get("reference_onset_to_full_throttle_m")
        ),
        "comparison_onset_to_full_throttle_m": _safe_float(
            result.get("comparison_onset_to_full_throttle_m")
        ),
        "comparison_minus_reference_m": _safe_float(
            result.get("comparison_minus_reference_m")
        ),
        "reason": result.get("reason"),
        "observational_only": True,
    }


def _candidate_selection_key(candidate):
    status_score = 1 if candidate.get("status") == "VALID" else 0
    global_rank = candidate.get("episode_global_rank")
    try:
        global_rank = int(global_rank)
    except (TypeError, ValueError):
        global_rank = 10**9
    action_loss = _safe_float(candidate.get("action_time_loss_s")) or 0.0
    return (-status_score, global_rank, -action_loss)


def _deduplicated_occurrences(comparisons):
    """One observation per (reference lap, comparison lap, reference event)."""
    buckets = defaultdict(list)

    for comparison_output in comparisons:
        if not isinstance(comparison_output, dict):
            continue

        reference_lap = _safe_int(comparison_output.get("reference_lap"))
        comparison_lap = _safe_int(comparison_output.get("comparison_lap"))

        for episode in _episode_ranking(comparison_output):
            if not isinstance(episode, dict):
                continue

            result = episode.get(
                "throttle_full_throttle_attainment_comparison"
            )
            if not isinstance(result, dict):
                continue

            reference_event_id = result.get("reference_event_id")
            if not reference_event_id:
                continue

            candidate = _compact_candidate(
                comparison_output,
                episode,
                result,
            )

            key = (
                reference_lap,
                comparison_lap,
                str(reference_event_id),
            )
            buckets[key].append(candidate)

    deduplicated = []

    for key in sorted(
        buckets,
        key=lambda item: (
            item[0] if item[0] is not None else 10**9,
            item[1] if item[1] is not None else 10**9,
            item[2],
        ),
    ):
        rows = buckets[key]
        signatures = {_candidate_signature(row) for row in rows}
        winner = sorted(rows, key=_candidate_selection_key)[0]
        winner = dict(winner)
        winner["duplicate_episode_count"] = max(0, len(rows) - 1)
        winner["duplicate_conflict"] = len(signatures) > 1

        if winner["duplicate_conflict"]:
            # Conflicting duplicate evidence is preserved but excluded from
            # recurrence support. Python does not guess which episode is right.
            winner["status"] = "CONFLICT"
            winner["relative_direction"] = None
            winner["reason"] = "conflicting_duplicate_episode_assignments"

        deduplicated.append(winner)

    return deduplicated


def _pattern_for_group(reference_lap, reference_event_id, rows, total_comparisons):
    valid_rows = [
        row
        for row in rows
        if row.get("status") == "VALID"
        and row.get("relative_direction") in SUPPORTED_DIRECTIONS
    ]
    unavailable_rows = [row for row in rows if row.get("status") == "UNAVAILABLE"]
    conflict_rows = [row for row in rows if row.get("status") == "CONFLICT"]

    counts = Counter(row.get("relative_direction") for row in valid_rows)
    ordered_counts = {
        direction: counts.get(direction, 0)
        for direction in SUPPORTED_DIRECTIONS
        if counts.get(direction, 0) > 0
    }

    selected_direction = None
    selected_count = 0
    top_directions = []

    if counts:
        selected_count = max(counts.values())
        top_directions = sorted(
            [
                direction
                for direction, count in counts.items()
                if count == selected_count
            ]
        )
        if len(top_directions) == 1:
            selected_direction = top_directions[0]

    is_repeated = bool(
        selected_direction
        and selected_count >= FULL_THROTTLE_RECURRENCE_MIN_SUPPORT_COUNT
    )

    distinct_valid_directions = len(counts)
    if not is_repeated:
        recurrence_status = "NOT_REPEATED"
    elif distinct_valid_directions == 1:
        recurrence_status = "REPEATED_CONSISTENT"
    else:
        recurrence_status = "REPEATED_WITH_MIXED_EVIDENCE"

    support_rows = [
        row
        for row in valid_rows
        if row.get("relative_direction") == selected_direction
    ] if selected_direction else []

    timing_delta_median = None
    timing_delta_min = None
    timing_delta_max = None

    if DIRECTION_PATTERN_KIND.get(selected_direction) == "timing":
        timing_values = [
            row.get("comparison_minus_reference_m")
            for row in support_rows
            if _safe_float(row.get("comparison_minus_reference_m")) is not None
        ]
        if timing_values:
            timing_values = [float(value) for value in timing_values]
            timing_delta_median = float(statistics.median(timing_values))
            timing_delta_min = min(timing_values)
            timing_delta_max = max(timing_values)

    observed_comparison_laps = sorted(
        {
            row.get("comparison_lap")
            for row in rows
            if row.get("comparison_lap") is not None
        }
    )
    support_comparison_laps = sorted(
        {
            row.get("comparison_lap")
            for row in support_rows
            if row.get("comparison_lap") is not None
        }
    )

    valid_count = len(valid_rows)
    support_fraction = (
        selected_count / valid_count
        if valid_count > 0 and selected_direction
        else None
    )

    return {
        "physical_point_id": f"full_throttle:{reference_event_id}",
        "reference_lap": reference_lap,
        "reference_event_id": reference_event_id,
        "pattern_kind": DIRECTION_PATTERN_KIND.get(selected_direction),
        "selected_direction": selected_direction,
        "recurrence_status": recurrence_status,
        "is_repeated": is_repeated,
        "is_consistent": recurrence_status == "REPEATED_CONSISTENT",
        "support_count": selected_count if selected_direction else 0,
        "valid_observation_count": valid_count,
        "unavailable_observation_count": len(unavailable_rows),
        "conflict_observation_count": len(conflict_rows),
        "observed_comparison_count": len(observed_comparison_laps),
        "missing_comparison_count": max(
            0,
            total_comparisons - len(observed_comparison_laps),
        ),
        "support_fraction_of_valid": _safe_float(support_fraction),
        "direction_counts": ordered_counts,
        "support_comparison_laps": support_comparison_laps,
        "observed_comparison_laps": observed_comparison_laps,
        "reference_attainment_m_median": _median(
            row.get("reference_attainment_m") for row in support_rows
        ),
        "comparison_attainment_m_median": _median(
            row.get("comparison_attainment_m") for row in support_rows
        ),
        "comparison_minus_reference_m_median": timing_delta_median,
        "comparison_minus_reference_m_min": timing_delta_min,
        "comparison_minus_reference_m_max": timing_delta_max,
        "observations": sorted(
            rows,
            key=lambda row: (
                row.get("comparison_lap")
                if row.get("comparison_lap") is not None
                else 10**9,
                row.get("episode_global_rank")
                if isinstance(row.get("episode_global_rank"), int)
                else 10**9,
            ),
        ),
        "observational_only": True,
        "affects_ranking": False,
        "affects_session_priority": False,
        "authorized_coaching": False,
    }


def build_full_throttle_attainment_recurrence(comparisons):
    comparisons = comparisons if isinstance(comparisons, list) else []
    occurrences = _deduplicated_occurrences(comparisons)

    groups = defaultdict(list)
    for row in occurrences:
        reference_event_id = row.get("reference_event_id")
        if not reference_event_id:
            continue
        key = (row.get("reference_lap"), reference_event_id)
        groups[key].append(row)

    patterns = []
    for (reference_lap, reference_event_id), rows in sorted(
        groups.items(),
        key=lambda item: (
            item[0][0] if item[0][0] is not None else 10**9,
            item[0][1],
        ),
    ):
        patterns.append(
            _pattern_for_group(
                reference_lap,
                reference_event_id,
                rows,
                len(comparisons),
            )
        )

    repeated = [pattern for pattern in patterns if pattern.get("is_repeated")]
    consistent = [
        pattern
        for pattern in repeated
        if pattern.get("recurrence_status") == "REPEATED_CONSISTENT"
    ]

    return {
        "version": FULL_THROTTLE_RECURRENCE_VERSION,
        "schema_version": FULL_THROTTLE_RECURRENCE_SCHEMA_VERSION,
        "config": full_throttle_recurrence_config_summary(),
        "comparison_count": len(comparisons),
        "physical_point_count": len(patterns),
        "repeated_pattern_count": len(repeated),
        "consistent_repeated_pattern_count": len(consistent),
        "timing_repeated_pattern_count": sum(
            1 for pattern in repeated if pattern.get("pattern_kind") == "timing"
        ),
        "attainment_state_repeated_pattern_count": sum(
            1
            for pattern in repeated
            if pattern.get("pattern_kind") == "attainment_state"
        ),
        "patterns": patterns,
        "policy": "observational_only_no_ranking_no_session_priority_no_coaching",
    }


def enrich_analysis_with_full_throttle_attainment_recurrence(analysis_output):
    """Session-level in-place enrichment after all comparisons are built."""
    if not isinstance(analysis_output, dict):
        return analysis_output

    comparisons = analysis_output.get("comparisons", [])
    analysis_output["full_throttle_attainment_recurrence"] = (
        build_full_throttle_attainment_recurrence(comparisons)
    )
    return analysis_output
